sudo: false
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn prepare
  - yarn validate
  - yarn bundlesize
after_success:
  - npx codecov
branches:
  only:
    - master