sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - export TZ=Europe/Paris
script:
  - npm start build
  - npm start validate
after_success:
  - npx codecov
branches:
  only:
    - master