import addDays from 'date-fns/fp/addDays'
import setHours from 'date-fns/fp/setHours'
import startOfHour from 'date-fns/startOfHour'

const today = new Date()
const tomorrow = addDays(1, today)

export default [
  {
    id: 1,
    title: 'nisl duis bibendum felis',
    start: '2017-09-15T17:12:35Z',
    end: '2017-09-27T04:05:33Z',
    allDay: true,
    color: '#c5f650',
  },
  {
    id: 2,
    title: 'leo rhoncus sed vestibulum',
    start: '2017-10-11T00:24:58Z',
    end: '2017-11-24T20:02:47Z',
    allDay: true,
    color: '#8d9e50',
  },
  {
    id: 3,
    title: 'maecenas tincidunt lacus at velit',
    start: '2017-09-30T18:14:20Z',
    end: '2017-11-05T15:19:08Z',
    allDay: true,
    color: '#8057b5',
  },
  {
    id: 4,
    title: 'mauris eget',
    start: '2017-10-07T00:23:40Z',
    end: '2017-11-20T12:55:01Z',
    allDay: true,
    color: '#4edcc6',
  },
  {
    id: 5,
    title: 'ac est lacinia nisi venenatis',
    start: '2017-08-30T20:29:18Z',
    end: '2017-12-01T14:18:47Z',
    allDay: true,
    color: '#708004',
  },
  {
    id: 1,
    title: 'mauris eget massa tempor convallis',
    start: '2017-09-05T20:12:46Z',
    end: '2017-09-07T09:38:37Z',
    allDay: true,
    color: '#03995d',
  },
  {
    id: 2,
    title: 'platea dictumst',
    start: '2017-09-04T08:23:16Z',
    end: '2017-09-04T08:51:11Z',
    allDay: false,
    color: '#e56ba3',
  },
  {
    id: 3,
    title: 'massa donec',
    allDay: '2017-09-06T02:04:32Z',
    color: '#bdc89c',
  },
  {
    id: 4,
    title: 'arcu sed augue aliquam erat',
    start: '2017-09-08T09:27:09Z',
    end: '2017-09-10T10:41:33Z',
    allDay: true,
    color: '#6ba768',
  },
  {
    id: 5,
    title: 'porttitor',
    allDay: '2017-09-07T11:25:03Z',
    color: '#18b417',
  },
  {
    allDay: false,
    start: startOfHour(setHours(1, tomorrow)),
    end: startOfHour(setHours(5, tomorrow)),
    title: 'Before',
    email: 'email@gmail.com',
    accepted: true,
    color: '#1234AE',
  },
  {
    allDay: false,
    start: startOfHour(setHours(20, tomorrow)),
    end: startOfHour(setHours(23, tomorrow)),
    title: 'After',
    email: 'email@gmail.com',
    accepted: true,
    color: '#1234AE',
  },
  {
    allDay: false,
    start: startOfHour(setHours(10, tomorrow)),
    end: startOfHour(setHours(13, tomorrow)),
    title: 'CM JS',
    email: 'email@gmail.com',
    accepted: true,
    color: '#AFED23',
  },
  {
    allDay: false,
    start: startOfHour(setHours(10, today)),
    end: startOfHour(setHours(13, today)),
    title: 'CM Feel Good',
    email: 'email@gmail.com',
    accepted: true,
    color: '#AFED23',
  },
  {
    allDay: false,
    start: startOfHour(setHours(9, today)),
    end: startOfHour(setHours(11, today)),
    title: 'CM Java',
    email: 'email@gmail.com',
    accepted: true,
    color: '#AFED23',
  },
  {
    allDay: false,
    start: startOfHour(setHours(14, tomorrow)),
    end: startOfHour(setHours(16, tomorrow)),
    title: 'Test',
    email: 'email@gmail.com',
    accepted: true,
  },
  {
    allDay: false,
    start: startOfHour(setHours(14, tomorrow)),
    end: startOfHour(setHours(15, tomorrow)),
    title: 'Test 2',
    email: 'email@gmail.com',
    accepted: true,
  },
  {
    allDay: false,
    start: startOfHour(setHours(17, tomorrow)),
    end: startOfHour(setHours(19, tomorrow)),
    title: 'Test 3',
    email: 'email@gmail.com',
    accepted: true,
  },
  {
    allDay: false,
    start: startOfHour(setHours(13, tomorrow)),
    end: startOfHour(setHours(20, tomorrow)),
    title: 'Test 4',
    email: 'email@gmail.com',
    accepted: true,
  },
  {
    allDay: false,
    start: startOfHour(setHours(9, tomorrow)),
    end: startOfHour(setHours(11, tomorrow)),
    title: 'Test 5',
    email: 'email@gmail.com',
    accepted: true,
  },
  {
    allDay: startOfHour(setHours(0, tomorrow)),
    title: 'Bid',
    email: 'email@gmail.com',
    accepted: true,
  },
  {
    allDay: false,
    start: startOfHour(setHours(14, today)),
    end: startOfHour(setHours(20, today)),
    title: 'Gouter',
    email: 'email@gmail.com',
    accepted: false,
  },
  {
    allDay: startOfHour(setHours(0, today)),
    title: 'formation JS',
    email: 'email@gmail.com',
    accepted: null,
  },
  {
    allDay: startOfHour(setHours(0, today)),
    title: 'formation Java',
    email: 'email@gmail.com',
    accepted: null,
  },
  {
    allDay: true,
    start: startOfHour(setHours(14, today)),
    end: startOfHour(setHours(20, addDays(3, today))),
    title: 'formation Docker',
    email: 'email@gmail.com',
    accepted: null,
  },
  {
    allDay: false,
    start: startOfHour(setHours(19, today)),
    end: startOfHour(setHours(12, tomorrow)),
    title: 'test chavauche',
    email: 'email@gmail.com',
    accepted: null,
  },
]
